theme: jekyll-theme-minimal
logo: zhaoxinfan2.jpg
description: This is  Zhaoxin Fan's homepage. Zhaoxin is a PhD student at Renmin University of China. He now is focus on reasearching 3D vision related tasks. His goal is to build a meta world to brige the gap between real world and the virtual worldã€‚
